### ISSUE TITLE
Explainer: Why we see new mMag on an identical rupture in COVVY vs UHU

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#92]
We have two rupture sets that produce different mMag for the equivalent rupture. 

RmlsZTozMDMuMEJCOVVY was [produced here](http://simple-toshi-ui.s3-website-ap-southeast-2.amazonaws.com/RuptureGenerationTask/UnVwdHVyZUdlbmVyYXRpb25UYXNrOjk2RllETWk=) on May 25th,  on using FM=**CFM_0_9_SANSTVZ_D90** 
RmlsZToxNTQ3Ni4wZVBZUHU= was [produced here](http://simple-toshi-ui.s3-website-ap-southeast-2.amazonaws.com/RuptureGenerationTask/UnVwdHVyZUdlbmVyYXRpb25UYXNrOjU0MjJKaFdxVg==) on 28 Nov using FM= **CFM_0_9A_SANSTVZ_D90**

Both used Scaling Relation TMG_CRU_2017

The two 'almost identical' ruptures are seen here:

 - http://nzshm22-static-reports.s3-website-ap-southeast-2.amazonaws.com/opensha/DATA/RmlsZTozMDMuMEJCOVVY/DiagnosticsReport/hist_rup_pages/hist_rup_651898.html
 - http://nzshm22-static-reports.s3-website-ap-southeast-2.amazonaws.com/opensha/DATA/RmlsZToxNTQ3Ni4wZVBZUHU=/DiagnosticsReport/hist_rup_pages/hist_rup_275116.html

**Comment by voj** [comment]
The magnitude of these two ruptures should be identical, considering that they have identical (or near-identical) area and both rupture sets were supposed to have been created with the same scaling relationship.

I have not been able to reproduce the 8.6 magnitude (UHU). I always get the 8.4 magnitude (as in COVVY).

- re-calculated the magnitude for the UHU file: 8.4
- re-created the rupture with the commits used at the time of UHU and the settings as in toshi: 8.4
- re-created the rupture with the current main: 8.4

The opensha commit as documented for the UHU rupture is a local commit by @chrisbc. It branched off `98d3784d27946a1e61a7cd02e9a3f3d422700cd4` Chris assures me nothing relevant had changed on that branch.

It's a bit of a mystery why the rupture's magnitude in that file is 8.6 instead of the 8.4 every attempt at reproduction has yielded. It might be that undocumented, uncommitted local changes were present when the rupture set was built. This will be avoided by the new github action-based release mechanism.
